[DATA]
base_path = /path/to/project/root
name = EXPERIMENT_NAME

# Condition name tags and data file locations
# condition name tag = data csv file location
0 = DATA_PATH_0.csv
1 = DATA_PATH_1.csv
2 = DATA_PATH_2.csv
... = ...
