[DATA]
base_path = /path/to/data
name = DATA_NAME

# # run.py -A condition_a -B condition_b --config PATH_TO_CONFIG
#condition_a = #...
#condition_b = #...

# TODO: Missing two condition names, specifed by required arguments `-A` and `-B`
