[DATA]
base_path = /path/to/data
name = DATA_NAME
# Or, use a mock data (form python pickle file):
#name = MOCK

# # run.py -A 0 -B 1 --config PATH_TO_CONFIG
0 = #...
1 = #...

# TODO: Missing two condition names, specifed by required arguments `-A` and `-B`
